name: Publish Podcast Episodes

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Create podcasts config
        run: |
          cat > podcasts.json << 'EOF'
          [
            {
              "id": "pensieriincodice",
              "name": "Pensieri in Codice",
              "feed_url": "${{ vars.PODCAST1_RSS_URL }}",
              "template": "${{ vars.PODCAST1_TEMPLATE }}"
            },
            {
              "id": "goodvibrations",
              "name": "Pensieri in Codice",
              "feed_url": "${{ vars.PODCAST2_RSS_URL }}",
              "template": "${{ vars.PODCAST2_TEMPLATE }}"
            }
          ]
          EOF

      - name: Run publish script
        env:
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
        run: php publish.php

      - name: Commit tracking files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add published_episodes_*.txt
          git diff --staged --quiet || git commit -m "Update published episodes [skip ci]"
          git push