name: Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Execute
        run: php -v

      - name: Create report file
        run: date +%s > report.txt
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
