name: Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Execute
        env:
          PODCAST_RSS_URL: ${{ vars.PODCAST_RSS_URL }}
          MASTODON_TOKEN: ${{ secrets.MASTODON_TOKEN }}
          MASTODON_MESSAGE_TEMPLATE: ${{ vars.MASTODON_MESSAGE_TEMPLATE }}
        run: php ./publish.php

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
